[
    { 
        code_activite: 'XX1J', 
        nom_add_on: '4CAD Master', 
        version_commerciale: 'N/A', 
        remarque: 'Add-on technique de base',
        brique_aero: ['Inclus'],
        brique_mro: ['Inclus'],
        v6: [],
        v7: [],
        pu9: [],
        v11_inférieure_a_v11_18: [],
        v11_18: [],
        v11_20: [],
        v12_inférieure_a_v12_28: [],
        v12_28: [],
        v12_29: [],
    },
    { 
        code_activite: 'XX1JA', 
        nom_add_on: '4CAD Suivi atelier', 
        version_commerciale: ['< V4.2','V4.2'], 
        remarque: 'Nouveau JDK & Nouvelle IHM ; Génération des PR & EQ',
        brique_aero: ['Inclus'],
        brique_mro: ['Inclus'],
        v6: [],
        v7: [],
        pu9: [],
        v11_inférieure_a_v11_18: [],
        v11_18: [],
        v11_20: [],
        v12_inférieure_a_v12_28: [],
        v12_28: [],
        v12_29: [],
    },
    { 
        code_activite: 151, 
        nom_add_on: 'Alan B. Shepard, Jr.', 
        version_commerciale: 'Astronaut', 
        remarque: 1959,
        brique_aero: ['MR-3', 'Apollo 14'],
        brique_mro: [],
        v6: [],
        v7: [],
        pu9: [],
        v11_inférieure_a_v11_18: [],
        v11_18: [],
        v11_20: [],
        v12_inférieure_a_v12_28: [],
        v12_28: [],
        v12_29: [],
    },
    { 
        code_activite: 151, 
        nom_add_on: 'Alan B. Shepard, Jr.', 
        version_commerciale: 'Astronaut', 
        remarque: 1959,
        brique_aero: ['MR-3', 'Apollo 14'],
        brique_mro: [],
        v6: [],
        v7: [],
        pu9: [],
        v11_inférieure_a_v11_18: [],
        v11_18: [],
        v11_20: [],
        v12_inférieure_a_v12_28: [],
        v12_28: [],
        v12_29: [],
    },
    { 
        code_activite: 151, 
        nom_add_on: 'Alan B. Shepard, Jr.', 
        version_commerciale: 'Astronaut', 
        remarque: 1959,
        brique_aero: ['MR-3', 'Apollo 14'],
        brique_mro: [],
        v6: [],
        v7: [],
        pu9: [],
        v11_inférieure_a_v11_18: [],
        v11_18: [],
        v11_20: [],
        v12_inférieure_a_v12_28: [],
        v12_28: [],
        v12_29: [],
    },
];